# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Happy Wallet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManagerSwift'
  pod 'lottie-ios'
  pod 'SwiftMessages'
  pod 'SDWebImage'
  pod "SJSwiftSideMenuController"

end
